// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadinessStatus int32

const (
	ReadinessStatus_READINESS_STATUS_UNSPECIFIED ReadinessStatus = 0
	ReadinessStatus_READINESS_STATUS_READY       ReadinessStatus = 1
	ReadinessStatus_READINESS_STATUS_NOT_READY   ReadinessStatus = 2
	ReadinessStatus_READINESS_STATUS_DEGRADED    ReadinessStatus = 3
)

// Enum value maps for ReadinessStatus.
var (
	ReadinessStatus_name = map[int32]string{
		0: "READINESS_STATUS_UNSPECIFIED",
		1: "READINESS_STATUS_READY",
		2: "READINESS_STATUS_NOT_READY",
		3: "READINESS_STATUS_DEGRADED",
	}
	ReadinessStatus_value = map[string]int32{
		"READINESS_STATUS_UNSPECIFIED": 0,
		"READINESS_STATUS_READY":       1,
		"READINESS_STATUS_NOT_READY":   2,
		"READINESS_STATUS_DEGRADED":    3,
	}
)

func (x ReadinessStatus) Enum() *ReadinessStatus {
	p := new(ReadinessStatus)
	*p = x
	return p
}

func (x ReadinessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadinessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (ReadinessStatus) Type() protoreflect.EnumType {
	return &file_agent_plugin_v1_plugin_proto_enumTypes[0]
}

func (x ReadinessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadinessStatus.Descriptor instead.
func (ReadinessStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
		3: "HEALTH_STATUS_DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
		"HEALTH_STATUS_DEGRADED":    3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_agent_plugin_v1_plugin_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type ShutdownMode int32

const (
	ShutdownMode_SHUTDOWN_MODE_UNSPECIFIED ShutdownMode = 0
	ShutdownMode_SHUTDOWN_MODE_GRACEFUL    ShutdownMode = 1
	ShutdownMode_SHUTDOWN_MODE_IMMEDIATE   ShutdownMode = 2
)

// Enum value maps for ShutdownMode.
var (
	ShutdownMode_name = map[int32]string{
		0: "SHUTDOWN_MODE_UNSPECIFIED",
		1: "SHUTDOWN_MODE_GRACEFUL",
		2: "SHUTDOWN_MODE_IMMEDIATE",
	}
	ShutdownMode_value = map[string]int32{
		"SHUTDOWN_MODE_UNSPECIFIED": 0,
		"SHUTDOWN_MODE_GRACEFUL":    1,
		"SHUTDOWN_MODE_IMMEDIATE":   2,
	}
)

func (x ShutdownMode) Enum() *ShutdownMode {
	p := new(ShutdownMode)
	*p = x
	return p
}

func (x ShutdownMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShutdownMode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (ShutdownMode) Type() protoreflect.EnumType {
	return &file_agent_plugin_v1_plugin_proto_enumTypes[2]
}

func (x ShutdownMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShutdownMode.Descriptor instead.
func (ShutdownMode) EnumDescriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

// ToolHints are untrusted annotations. Risk, concurrency, and authorization
// remain application-owned catalog/policy decisions.
type RiskHint int32

const (
	RiskHint_RISK_HINT_UNSPECIFIED  RiskHint = 0
	RiskHint_RISK_HINT_READ_ONLY    RiskHint = 1
	RiskHint_RISK_HINT_STATE_CHANGE RiskHint = 2
	RiskHint_RISK_HINT_PRIVILEGED   RiskHint = 3
)

// Enum value maps for RiskHint.
var (
	RiskHint_name = map[int32]string{
		0: "RISK_HINT_UNSPECIFIED",
		1: "RISK_HINT_READ_ONLY",
		2: "RISK_HINT_STATE_CHANGE",
		3: "RISK_HINT_PRIVILEGED",
	}
	RiskHint_value = map[string]int32{
		"RISK_HINT_UNSPECIFIED":  0,
		"RISK_HINT_READ_ONLY":    1,
		"RISK_HINT_STATE_CHANGE": 2,
		"RISK_HINT_PRIVILEGED":   3,
	}
)

func (x RiskHint) Enum() *RiskHint {
	p := new(RiskHint)
	*p = x
	return p
}

func (x RiskHint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskHint) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_plugin_v1_plugin_proto_enumTypes[3].Descriptor()
}

func (RiskHint) Type() protoreflect.EnumType {
	return &file_agent_plugin_v1_plugin_proto_enumTypes[3]
}

func (x RiskHint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskHint.Descriptor instead.
func (RiskHint) EnumDescriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

type FailureCode int32

const (
	FailureCode_FAILURE_CODE_UNSPECIFIED       FailureCode = 0
	FailureCode_FAILURE_CODE_INVALID_ARGUMENT  FailureCode = 1
	FailureCode_FAILURE_CODE_NOT_FOUND         FailureCode = 2
	FailureCode_FAILURE_CODE_PERMISSION_DENIED FailureCode = 3
	FailureCode_FAILURE_CODE_CANCELED          FailureCode = 4
	FailureCode_FAILURE_CODE_DEADLINE_EXCEEDED FailureCode = 5
	FailureCode_FAILURE_CODE_OUTPUT_LIMIT      FailureCode = 6
	FailureCode_FAILURE_CODE_UNAVAILABLE       FailureCode = 7
	FailureCode_FAILURE_CODE_INTERNAL          FailureCode = 8
)

// Enum value maps for FailureCode.
var (
	FailureCode_name = map[int32]string{
		0: "FAILURE_CODE_UNSPECIFIED",
		1: "FAILURE_CODE_INVALID_ARGUMENT",
		2: "FAILURE_CODE_NOT_FOUND",
		3: "FAILURE_CODE_PERMISSION_DENIED",
		4: "FAILURE_CODE_CANCELED",
		5: "FAILURE_CODE_DEADLINE_EXCEEDED",
		6: "FAILURE_CODE_OUTPUT_LIMIT",
		7: "FAILURE_CODE_UNAVAILABLE",
		8: "FAILURE_CODE_INTERNAL",
	}
	FailureCode_value = map[string]int32{
		"FAILURE_CODE_UNSPECIFIED":       0,
		"FAILURE_CODE_INVALID_ARGUMENT":  1,
		"FAILURE_CODE_NOT_FOUND":         2,
		"FAILURE_CODE_PERMISSION_DENIED": 3,
		"FAILURE_CODE_CANCELED":          4,
		"FAILURE_CODE_DEADLINE_EXCEEDED": 5,
		"FAILURE_CODE_OUTPUT_LIMIT":      6,
		"FAILURE_CODE_UNAVAILABLE":       7,
		"FAILURE_CODE_INTERNAL":          8,
	}
)

func (x FailureCode) Enum() *FailureCode {
	p := new(FailureCode)
	*p = x
	return p
}

func (x FailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_plugin_v1_plugin_proto_enumTypes[4].Descriptor()
}

func (FailureCode) Type() protoreflect.EnumType {
	return &file_agent_plugin_v1_plugin_proto_enumTypes[4]
}

func (x FailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureCode.Descriptor instead.
func (FailureCode) EnumDescriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

// ProtocolVersion identifies one semantic pips domain protocol. It is
// negotiated independently from the bootstrap framing, manifest schema,
// plugin semantic version, artifact target, and persisted state schema.
type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// ProtocolRange describes the minor versions supported for one major.
type ProtocolRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	MinMinor      uint32                 `protobuf:"varint,2,opt,name=min_minor,json=minMinor,proto3" json:"min_minor,omitempty"`
	MaxMinor      uint32                 `protobuf:"varint,3,opt,name=max_minor,json=maxMinor,proto3" json:"max_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolRange) Reset() {
	*x = ProtocolRange{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolRange) ProtoMessage() {}

func (x *ProtocolRange) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolRange.ProtoReflect.Descriptor instead.
func (*ProtocolRange) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolRange) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolRange) GetMinMinor() uint32 {
	if x != nil {
		return x.MinMinor
	}
	return 0
}

func (x *ProtocolRange) GetMaxMinor() uint32 {
	if x != nil {
		return x.MaxMinor
	}
	return 0
}

// CapabilityVersion identifies a versioned capability family. Capability
// names and versions are declarations; the application still decides which
// capabilities are granted.
type CapabilityVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Major         uint32                 `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	MinMinor      uint32                 `protobuf:"varint,3,opt,name=min_minor,json=minMinor,proto3" json:"min_minor,omitempty"`
	MaxMinor      uint32                 `protobuf:"varint,4,opt,name=max_minor,json=maxMinor,proto3" json:"max_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityVersion) Reset() {
	*x = CapabilityVersion{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityVersion) ProtoMessage() {}

func (x *CapabilityVersion) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityVersion.ProtoReflect.Descriptor instead.
func (*CapabilityVersion) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilityVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapabilityVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *CapabilityVersion) GetMinMinor() uint32 {
	if x != nil {
		return x.MinMinor
	}
	return 0
}

func (x *CapabilityVersion) GetMaxMinor() uint32 {
	if x != nil {
		return x.MaxMinor
	}
	return 0
}

// CapabilityGrant records the application decision for one declared
// capability. A plugin declaration or annotation never grants itself access.
type CapabilityGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    *CapabilityVersion     `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityGrant) Reset() {
	*x = CapabilityGrant{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityGrant) ProtoMessage() {}

func (x *CapabilityGrant) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityGrant.ProtoReflect.Descriptor instead.
func (*CapabilityGrant) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CapabilityGrant) GetCapability() *CapabilityVersion {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *CapabilityGrant) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type PluginIdentity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SemanticVersion string                 `protobuf:"bytes,2,opt,name=semantic_version,json=semanticVersion,proto3" json:"semantic_version,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginIdentity) Reset() {
	*x = PluginIdentity{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginIdentity) ProtoMessage() {}

func (x *PluginIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginIdentity.ProtoReflect.Descriptor instead.
func (*PluginIdentity) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginIdentity) GetSemanticVersion() string {
	if x != nil {
		return x.SemanticVersion
	}
	return ""
}

func (x *PluginIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginIdentity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// StateSchema is an identity for host-owned durable state. State migration is
// intentionally not part of this MVP; the schema is reported so later phases
// can reject incompatible state rather than guessing.
type StateSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSchema) Reset() {
	*x = StateSchema{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSchema) ProtoMessage() {}

func (x *StateSchema) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSchema.ProtoReflect.Descriptor instead.
func (*StateSchema) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *StateSchema) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StateSchema) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Provenance is an informational echo from the installed artifact. It is not
// a substitute for manifest verification, signatures, or host policy.
type Provenance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Publisher      string                 `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ArtifactDigest string                 `protobuf:"bytes,3,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Provenance) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Provenance) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Provenance) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

// ResourceLimits communicates negotiated budgets. The application remains the
// authority and may choose stricter values than the plugin advertises.
type ResourceLimits struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxInputBytes      uint64                 `protobuf:"varint,1,opt,name=max_input_bytes,json=maxInputBytes,proto3" json:"max_input_bytes,omitempty"`
	MaxOutputBytes     uint64                 `protobuf:"varint,2,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	MaxEventBytes      uint64                 `protobuf:"varint,3,opt,name=max_event_bytes,json=maxEventBytes,proto3" json:"max_event_bytes,omitempty"`
	MaxProgressEvents  uint32                 `protobuf:"varint,4,opt,name=max_progress_events,json=maxProgressEvents,proto3" json:"max_progress_events,omitempty"`
	MaxConcurrentCalls uint32                 `protobuf:"varint,5,opt,name=max_concurrent_calls,json=maxConcurrentCalls,proto3" json:"max_concurrent_calls,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceLimits) GetMaxInputBytes() uint64 {
	if x != nil {
		return x.MaxInputBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxOutputBytes() uint64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxEventBytes() uint64 {
	if x != nil {
		return x.MaxEventBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxProgressEvents() uint32 {
	if x != nil {
		return x.MaxProgressEvents
	}
	return 0
}

func (x *ResourceLimits) GetMaxConcurrentCalls() uint32 {
	if x != nil {
		return x.MaxConcurrentCalls
	}
	return 0
}

type DescribeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApplicationProtocol *ProtocolVersion       `protobuf:"bytes,1,opt,name=application_protocol,json=applicationProtocol,proto3" json:"application_protocol,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *DescribeRequest) GetApplicationProtocol() *ProtocolVersion {
	if x != nil {
		return x.ApplicationProtocol
	}
	return nil
}

type DescribeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Identity            *PluginIdentity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	ApplicationProtocol *ProtocolRange         `protobuf:"bytes,2,opt,name=application_protocol,json=applicationProtocol,proto3" json:"application_protocol,omitempty"`
	Capabilities        []*CapabilityVersion   `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	StateSchemas        []*StateSchema         `protobuf:"bytes,4,rep,name=state_schemas,json=stateSchemas,proto3" json:"state_schemas,omitempty"`
	Provenance          *Provenance            `protobuf:"bytes,5,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Limits              *ResourceLimits        `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *DescribeResponse) GetIdentity() *PluginIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *DescribeResponse) GetApplicationProtocol() *ProtocolRange {
	if x != nil {
		return x.ApplicationProtocol
	}
	return nil
}

func (x *DescribeResponse) GetCapabilities() []*CapabilityVersion {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DescribeResponse) GetStateSchemas() []*StateSchema {
	if x != nil {
		return x.StateSchemas
	}
	return nil
}

func (x *DescribeResponse) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *DescribeResponse) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type ConfigureRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApplicationProtocol *ProtocolVersion       `protobuf:"bytes,1,opt,name=application_protocol,json=applicationProtocol,proto3" json:"application_protocol,omitempty"`
	Grants              []*CapabilityGrant     `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	Limits              *ResourceLimits        `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	// Canonical JSON object owned by the application/plugin contract. It is
	// opaque to this transport package and must not contain ambient secrets.
	ConfigurationJson []byte `protobuf:"bytes,4,opt,name=configuration_json,json=configurationJson,proto3" json:"configuration_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigureRequest) GetApplicationProtocol() *ProtocolVersion {
	if x != nil {
		return x.ApplicationProtocol
	}
	return nil
}

func (x *ConfigureRequest) GetGrants() []*CapabilityGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *ConfigureRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ConfigureRequest) GetConfigurationJson() []byte {
	if x != nil {
		return x.ConfigurationJson
	}
	return nil
}

type ConfigureResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EnabledCapabilities []*CapabilityVersion   `protobuf:"bytes,1,rep,name=enabled_capabilities,json=enabledCapabilities,proto3" json:"enabled_capabilities,omitempty"`
	EffectiveLimits     *ResourceLimits        `protobuf:"bytes,2,opt,name=effective_limits,json=effectiveLimits,proto3" json:"effective_limits,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigureResponse) GetEnabledCapabilities() []*CapabilityVersion {
	if x != nil {
		return x.EnabledCapabilities
	}
	return nil
}

func (x *ConfigureResponse) GetEffectiveLimits() *ResourceLimits {
	if x != nil {
		return x.EffectiveLimits
	}
	return nil
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReadinessStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=agent.plugin.v1.ReadinessStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ReadyResponse) GetStatus() ReadinessStatus {
	if x != nil {
		return x.Status
	}
	return ReadinessStatus_READINESS_STATUS_UNSPECIFIED
}

func (x *ReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=agent.plugin.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ActiveCalls   uint32                 `protobuf:"varint,3,opt,name=active_calls,json=activeCalls,proto3" json:"active_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetActiveCalls() uint32 {
	if x != nil {
		return x.ActiveCalls
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          ShutdownMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=agent.plugin.v1.ShutdownMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ShutdownRequest) GetMode() ShutdownMode {
	if x != nil {
		return x.Mode
	}
	return ShutdownMode_SHUTDOWN_MODE_UNSPECIFIED
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ShutdownResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

type ToolHints struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Risk            RiskHint               `protobuf:"varint,1,opt,name=risk,proto3,enum=agent.plugin.v1.RiskHint" json:"risk,omitempty"`
	ConcurrencySafe bool                   `protobuf:"varint,2,opt,name=concurrency_safe,json=concurrencySafe,proto3" json:"concurrency_safe,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolHints) Reset() {
	*x = ToolHints{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolHints) ProtoMessage() {}

func (x *ToolHints) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolHints.ProtoReflect.Descriptor instead.
func (*ToolHints) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ToolHints) GetRisk() RiskHint {
	if x != nil {
		return x.Risk
	}
	return RiskHint_RISK_HINT_UNSPECIFIED
}

func (x *ToolHints) GetConcurrencySafe() bool {
	if x != nil {
		return x.ConcurrencySafe
	}
	return false
}

type ToolDescriptor struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// A UTF-8 JSON object containing the input schema. The schema is semantic
	// data, not a Go type or an authorization document.
	InputSchemaJson []byte     `protobuf:"bytes,4,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	Hints           *ToolHints `protobuf:"bytes,5,opt,name=hints,proto3" json:"hints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolDescriptor) Reset() {
	*x = ToolDescriptor{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDescriptor) ProtoMessage() {}

func (x *ToolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDescriptor.ProtoReflect.Descriptor instead.
func (*ToolDescriptor) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ToolDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDescriptor) GetInputSchemaJson() []byte {
	if x != nil {
		return x.InputSchemaJson
	}
	return nil
}

func (x *ToolDescriptor) GetHints() *ToolHints {
	if x != nil {
		return x.Hints
	}
	return nil
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDescriptor      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *ListToolsResponse) GetTools() []*ToolDescriptor {
	if x != nil {
		return x.Tools
	}
	return nil
}

type InvokeToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	InvocationId  string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ArgumentsJson []byte                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// The transport context/deadline is authoritative. This field is an
	// optional serialized echo for implementations that need one wire value.
	DeadlineUnixNanos int64 `protobuf:"varint,4,opt,name=deadline_unix_nanos,json=deadlineUnixNanos,proto3" json:"deadline_unix_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InvokeToolRequest) Reset() {
	*x = InvokeToolRequest{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeToolRequest) ProtoMessage() {}

func (x *InvokeToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeToolRequest.ProtoReflect.Descriptor instead.
func (*InvokeToolRequest) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *InvokeToolRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *InvokeToolRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvokeToolRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *InvokeToolRequest) GetDeadlineUnixNanos() int64 {
	if x != nil {
		return x.DeadlineUnixNanos
	}
	return 0
}

type ToolProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PercentMillis uint32                 `protobuf:"varint,2,opt,name=percent_millis,json=percentMillis,proto3" json:"percent_millis,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolProgress) Reset() {
	*x = ToolProgress{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolProgress) ProtoMessage() {}

func (x *ToolProgress) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolProgress.ProtoReflect.Descriptor instead.
func (*ToolProgress) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *ToolProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolProgress) GetPercentMillis() uint32 {
	if x != nil {
		return x.PercentMillis
	}
	return 0
}

func (x *ToolProgress) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type ToolContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolContent) Reset() {
	*x = ToolContent{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolContent) ProtoMessage() {}

func (x *ToolContent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolContent.ProtoReflect.Descriptor instead.
func (*ToolContent) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ToolContent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ToolContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ToolResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        []*ToolContent         `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	StructuredJson []byte                 `protobuf:"bytes,2,opt,name=structured_json,json=structuredJson,proto3" json:"structured_json,omitempty"`
	Truncated      bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *ToolResult) GetContent() []*ToolContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ToolResult) GetStructuredJson() []byte {
	if x != nil {
		return x.StructuredJson
	}
	return nil
}

func (x *ToolResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type FailureProblem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureProblem) Reset() {
	*x = FailureProblem{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureProblem) ProtoMessage() {}

func (x *FailureProblem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureProblem.ProtoReflect.Descriptor instead.
func (*FailureProblem) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *FailureProblem) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FailureProblem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FailureProblem) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *FailureProblem) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type ToolFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          FailureCode            `protobuf:"varint,1,opt,name=code,proto3,enum=agent.plugin.v1.FailureCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Problems      []*FailureProblem      `protobuf:"bytes,3,rep,name=problems,proto3" json:"problems,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	DetailsJson   []byte                 `protobuf:"bytes,5,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFailure) Reset() {
	*x = ToolFailure{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFailure) ProtoMessage() {}

func (x *ToolFailure) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFailure.ProtoReflect.Descriptor instead.
func (*ToolFailure) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *ToolFailure) GetCode() FailureCode {
	if x != nil {
		return x.Code
	}
	return FailureCode_FAILURE_CODE_UNSPECIFIED
}

func (x *ToolFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolFailure) GetProblems() []*FailureProblem {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *ToolFailure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ToolFailure) GetDetailsJson() []byte {
	if x != nil {
		return x.DetailsJson
	}
	return nil
}

// InvokeToolResponse is one ordered server-stream item. Progress is
// non-terminal; Result and Failure are terminal. A stream must contain exactly
// one terminal event and monotonically increasing, non-zero sequence values.
type InvokeToolResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*InvokeToolResponse_Progress
	//	*InvokeToolResponse_Result
	//	*InvokeToolResponse_Failure
	Payload       isInvokeToolResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeToolResponse) Reset() {
	*x = InvokeToolResponse{}
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeToolResponse) ProtoMessage() {}

func (x *InvokeToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_plugin_v1_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeToolResponse.ProtoReflect.Descriptor instead.
func (*InvokeToolResponse) Descriptor() ([]byte, []int) {
	return file_agent_plugin_v1_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *InvokeToolResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *InvokeToolResponse) GetPayload() isInvokeToolResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeToolResponse) GetProgress() *ToolProgress {
	if x != nil {
		if x, ok := x.Payload.(*InvokeToolResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *InvokeToolResponse) GetResult() *ToolResult {
	if x != nil {
		if x, ok := x.Payload.(*InvokeToolResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *InvokeToolResponse) GetFailure() *ToolFailure {
	if x != nil {
		if x, ok := x.Payload.(*InvokeToolResponse_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isInvokeToolResponse_Payload interface {
	isInvokeToolResponse_Payload()
}

type InvokeToolResponse_Progress struct {
	Progress *ToolProgress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type InvokeToolResponse_Result struct {
	Result *ToolResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type InvokeToolResponse_Failure struct {
	Failure *ToolFailure `protobuf:"bytes,4,opt,name=failure,proto3,oneof"`
}

func (*InvokeToolResponse_Progress) isInvokeToolResponse_Payload() {}

func (*InvokeToolResponse_Result) isInvokeToolResponse_Payload() {}

func (*InvokeToolResponse_Failure) isInvokeToolResponse_Payload() {}

var File_agent_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_agent_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cagent/plugin/v1/plugin.proto\x12\x0fagent.plugin.v1\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"_\n" +
	"\rProtocolRange\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x1b\n" +
	"\tmin_minor\x18\x02 \x01(\rR\bminMinor\x12\x1b\n" +
	"\tmax_minor\x18\x03 \x01(\rR\bmaxMinor\"w\n" +
	"\x11CapabilityVersion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05major\x18\x02 \x01(\rR\x05major\x12\x1b\n" +
	"\tmin_minor\x18\x03 \x01(\rR\bminMinor\x12\x1b\n" +
	"\tmax_minor\x18\x04 \x01(\rR\bmaxMinor\"o\n" +
	"\x0fCapabilityGrant\x12B\n" +
	"\n" +
	"capability\x18\x01 \x01(\v2\".agent.plugin.v1.CapabilityVersionR\n" +
	"capability\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\x90\x01\n" +
	"\x0ePluginIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10semantic_version\x18\x02 \x01(\tR\x0fsemanticVersion\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\";\n" +
	"\vStateSchema\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"k\n" +
	"\n" +
	"Provenance\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12'\n" +
	"\x0fartifact_digest\x18\x03 \x01(\tR\x0eartifactDigest\"\xec\x01\n" +
	"\x0eResourceLimits\x12&\n" +
	"\x0fmax_input_bytes\x18\x01 \x01(\x04R\rmaxInputBytes\x12(\n" +
	"\x10max_output_bytes\x18\x02 \x01(\x04R\x0emaxOutputBytes\x12&\n" +
	"\x0fmax_event_bytes\x18\x03 \x01(\x04R\rmaxEventBytes\x12.\n" +
	"\x13max_progress_events\x18\x04 \x01(\rR\x11maxProgressEvents\x120\n" +
	"\x14max_concurrent_calls\x18\x05 \x01(\rR\x12maxConcurrentCalls\"f\n" +
	"\x0fDescribeRequest\x12S\n" +
	"\x14application_protocol\x18\x01 \x01(\v2 .agent.plugin.v1.ProtocolVersionR\x13applicationProtocol\"\xa3\x03\n" +
	"\x10DescribeResponse\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.agent.plugin.v1.PluginIdentityR\bidentity\x12Q\n" +
	"\x14application_protocol\x18\x02 \x01(\v2\x1e.agent.plugin.v1.ProtocolRangeR\x13applicationProtocol\x12F\n" +
	"\fcapabilities\x18\x03 \x03(\v2\".agent.plugin.v1.CapabilityVersionR\fcapabilities\x12A\n" +
	"\rstate_schemas\x18\x04 \x03(\v2\x1c.agent.plugin.v1.StateSchemaR\fstateSchemas\x12;\n" +
	"\n" +
	"provenance\x18\x05 \x01(\v2\x1b.agent.plugin.v1.ProvenanceR\n" +
	"provenance\x127\n" +
	"\x06limits\x18\x06 \x01(\v2\x1f.agent.plugin.v1.ResourceLimitsR\x06limits\"\x89\x02\n" +
	"\x10ConfigureRequest\x12S\n" +
	"\x14application_protocol\x18\x01 \x01(\v2 .agent.plugin.v1.ProtocolVersionR\x13applicationProtocol\x128\n" +
	"\x06grants\x18\x02 \x03(\v2 .agent.plugin.v1.CapabilityGrantR\x06grants\x127\n" +
	"\x06limits\x18\x03 \x01(\v2\x1f.agent.plugin.v1.ResourceLimitsR\x06limits\x12-\n" +
	"\x12configuration_json\x18\x04 \x01(\fR\x11configurationJson\"\xb6\x01\n" +
	"\x11ConfigureResponse\x12U\n" +
	"\x14enabled_capabilities\x18\x01 \x03(\v2\".agent.plugin.v1.CapabilityVersionR\x13enabledCapabilities\x12J\n" +
	"\x10effective_limits\x18\x02 \x01(\v2\x1f.agent.plugin.v1.ResourceLimitsR\x0feffectiveLimits\"\x0e\n" +
	"\fReadyRequest\"c\n" +
	"\rReadyResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .agent.plugin.v1.ReadinessStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rHealthRequest\"\x84\x01\n" +
	"\x0eHealthResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.agent.plugin.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\factive_calls\x18\x03 \x01(\rR\vactiveCalls\"D\n" +
	"\x0fShutdownRequest\x121\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1d.agent.plugin.v1.ShutdownModeR\x04mode\".\n" +
	"\x10ShutdownResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x12\n" +
	"\x10ListToolsRequest\"e\n" +
	"\tToolHints\x12-\n" +
	"\x04risk\x18\x01 \x01(\x0e2\x19.agent.plugin.v1.RiskHintR\x04risk\x12)\n" +
	"\x10concurrency_safe\x18\x02 \x01(\bR\x0fconcurrencySafe\"\xb4\x01\n" +
	"\x0eToolDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x04 \x01(\fR\x0finputSchemaJson\x120\n" +
	"\x05hints\x18\x05 \x01(\v2\x1a.agent.plugin.v1.ToolHintsR\x05hints\"J\n" +
	"\x11ListToolsResponse\x125\n" +
	"\x05tools\x18\x01 \x03(\v2\x1f.agent.plugin.v1.ToolDescriptorR\x05tools\"\xa8\x01\n" +
	"\x11InvokeToolRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\x12.\n" +
	"\x13deadline_unix_nanos\x18\x04 \x01(\x03R\x11deadlineUnixNanos\"t\n" +
	"\fToolProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x0epercent_millis\x18\x02 \x01(\rR\rpercentMillis\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\"@\n" +
	"\vToolContent\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x8b\x01\n" +
	"\n" +
	"ToolResult\x126\n" +
	"\acontent\x18\x01 \x03(\v2\x1c.agent.plugin.v1.ToolContentR\acontent\x12'\n" +
	"\x0fstructured_json\x18\x02 \x01(\fR\x0estructuredJson\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"p\n" +
	"\x0eFailureProblem\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\"\xd7\x01\n" +
	"\vToolFailure\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.agent.plugin.v1.FailureCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\bproblems\x18\x03 \x03(\v2\x1f.agent.plugin.v1.FailureProblemR\bproblems\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12!\n" +
	"\fdetails_json\x18\x05 \x01(\fR\vdetailsJson\"\xe9\x01\n" +
	"\x12InvokeToolResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12;\n" +
	"\bprogress\x18\x02 \x01(\v2\x1d.agent.plugin.v1.ToolProgressH\x00R\bprogress\x125\n" +
	"\x06result\x18\x03 \x01(\v2\x1b.agent.plugin.v1.ToolResultH\x00R\x06result\x128\n" +
	"\afailure\x18\x04 \x01(\v2\x1c.agent.plugin.v1.ToolFailureH\x00R\afailureB\t\n" +
	"\apayload*\x8e\x01\n" +
	"\x0fReadinessStatus\x12 \n" +
	"\x1cREADINESS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16READINESS_STATUS_READY\x10\x01\x12\x1e\n" +
	"\x1aREADINESS_STATUS_NOT_READY\x10\x02\x12\x1d\n" +
	"\x19READINESS_STATUS_DEGRADED\x10\x03*\x83\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x03*f\n" +
	"\fShutdownMode\x12\x1d\n" +
	"\x19SHUTDOWN_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SHUTDOWN_MODE_GRACEFUL\x10\x01\x12\x1b\n" +
	"\x17SHUTDOWN_MODE_IMMEDIATE\x10\x02*t\n" +
	"\bRiskHint\x12\x19\n" +
	"\x15RISK_HINT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RISK_HINT_READ_ONLY\x10\x01\x12\x1a\n" +
	"\x16RISK_HINT_STATE_CHANGE\x10\x02\x12\x18\n" +
	"\x14RISK_HINT_PRIVILEGED\x10\x03*\xa5\x02\n" +
	"\vFailureCode\x12\x1c\n" +
	"\x18FAILURE_CODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dFAILURE_CODE_INVALID_ARGUMENT\x10\x01\x12\x1a\n" +
	"\x16FAILURE_CODE_NOT_FOUND\x10\x02\x12\"\n" +
	"\x1eFAILURE_CODE_PERMISSION_DENIED\x10\x03\x12\x19\n" +
	"\x15FAILURE_CODE_CANCELED\x10\x04\x12\"\n" +
	"\x1eFAILURE_CODE_DEADLINE_EXCEEDED\x10\x05\x12\x1d\n" +
	"\x19FAILURE_CODE_OUTPUT_LIMIT\x10\x06\x12\x1c\n" +
	"\x18FAILURE_CODE_UNAVAILABLE\x10\a\x12\x19\n" +
	"\x15FAILURE_CODE_INTERNAL\x10\b2\x96\x03\n" +
	"\vCoreService\x12O\n" +
	"\bDescribe\x12 .agent.plugin.v1.DescribeRequest\x1a!.agent.plugin.v1.DescribeResponse\x12R\n" +
	"\tConfigure\x12!.agent.plugin.v1.ConfigureRequest\x1a\".agent.plugin.v1.ConfigureResponse\x12F\n" +
	"\x05Ready\x12\x1d.agent.plugin.v1.ReadyRequest\x1a\x1e.agent.plugin.v1.ReadyResponse\x12I\n" +
	"\x06Health\x12\x1e.agent.plugin.v1.HealthRequest\x1a\x1f.agent.plugin.v1.HealthResponse\x12O\n" +
	"\bShutdown\x12 .agent.plugin.v1.ShutdownRequest\x1a!.agent.plugin.v1.ShutdownResponse2\xbb\x01\n" +
	"\fToolsService\x12R\n" +
	"\tListTools\x12!.agent.plugin.v1.ListToolsRequest\x1a\".agent.plugin.v1.ListToolsResponse\x12W\n" +
	"\n" +
	"InvokeTool\x12\".agent.plugin.v1.InvokeToolRequest\x1a#.agent.plugin.v1.InvokeToolResponse0\x01B0Z.github.com/rsbin/pips/agent/plugin/v1;pluginv1b\x06proto3"

var (
	file_agent_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_agent_plugin_v1_plugin_proto_rawDescData []byte
)

func file_agent_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_agent_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_agent_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_plugin_v1_plugin_proto_rawDesc), len(file_agent_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_agent_plugin_v1_plugin_proto_rawDescData
}

var file_agent_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_agent_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_agent_plugin_v1_plugin_proto_goTypes = []any{
	(ReadinessStatus)(0),       // 0: agent.plugin.v1.ReadinessStatus
	(HealthStatus)(0),          // 1: agent.plugin.v1.HealthStatus
	(ShutdownMode)(0),          // 2: agent.plugin.v1.ShutdownMode
	(RiskHint)(0),              // 3: agent.plugin.v1.RiskHint
	(FailureCode)(0),           // 4: agent.plugin.v1.FailureCode
	(*ProtocolVersion)(nil),    // 5: agent.plugin.v1.ProtocolVersion
	(*ProtocolRange)(nil),      // 6: agent.plugin.v1.ProtocolRange
	(*CapabilityVersion)(nil),  // 7: agent.plugin.v1.CapabilityVersion
	(*CapabilityGrant)(nil),    // 8: agent.plugin.v1.CapabilityGrant
	(*PluginIdentity)(nil),     // 9: agent.plugin.v1.PluginIdentity
	(*StateSchema)(nil),        // 10: agent.plugin.v1.StateSchema
	(*Provenance)(nil),         // 11: agent.plugin.v1.Provenance
	(*ResourceLimits)(nil),     // 12: agent.plugin.v1.ResourceLimits
	(*DescribeRequest)(nil),    // 13: agent.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),   // 14: agent.plugin.v1.DescribeResponse
	(*ConfigureRequest)(nil),   // 15: agent.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),  // 16: agent.plugin.v1.ConfigureResponse
	(*ReadyRequest)(nil),       // 17: agent.plugin.v1.ReadyRequest
	(*ReadyResponse)(nil),      // 18: agent.plugin.v1.ReadyResponse
	(*HealthRequest)(nil),      // 19: agent.plugin.v1.HealthRequest
	(*HealthResponse)(nil),     // 20: agent.plugin.v1.HealthResponse
	(*ShutdownRequest)(nil),    // 21: agent.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),   // 22: agent.plugin.v1.ShutdownResponse
	(*ListToolsRequest)(nil),   // 23: agent.plugin.v1.ListToolsRequest
	(*ToolHints)(nil),          // 24: agent.plugin.v1.ToolHints
	(*ToolDescriptor)(nil),     // 25: agent.plugin.v1.ToolDescriptor
	(*ListToolsResponse)(nil),  // 26: agent.plugin.v1.ListToolsResponse
	(*InvokeToolRequest)(nil),  // 27: agent.plugin.v1.InvokeToolRequest
	(*ToolProgress)(nil),       // 28: agent.plugin.v1.ToolProgress
	(*ToolContent)(nil),        // 29: agent.plugin.v1.ToolContent
	(*ToolResult)(nil),         // 30: agent.plugin.v1.ToolResult
	(*FailureProblem)(nil),     // 31: agent.plugin.v1.FailureProblem
	(*ToolFailure)(nil),        // 32: agent.plugin.v1.ToolFailure
	(*InvokeToolResponse)(nil), // 33: agent.plugin.v1.InvokeToolResponse
}
var file_agent_plugin_v1_plugin_proto_depIdxs = []int32{
	7,  // 0: agent.plugin.v1.CapabilityGrant.capability:type_name -> agent.plugin.v1.CapabilityVersion
	5,  // 1: agent.plugin.v1.DescribeRequest.application_protocol:type_name -> agent.plugin.v1.ProtocolVersion
	9,  // 2: agent.plugin.v1.DescribeResponse.identity:type_name -> agent.plugin.v1.PluginIdentity
	6,  // 3: agent.plugin.v1.DescribeResponse.application_protocol:type_name -> agent.plugin.v1.ProtocolRange
	7,  // 4: agent.plugin.v1.DescribeResponse.capabilities:type_name -> agent.plugin.v1.CapabilityVersion
	10, // 5: agent.plugin.v1.DescribeResponse.state_schemas:type_name -> agent.plugin.v1.StateSchema
	11, // 6: agent.plugin.v1.DescribeResponse.provenance:type_name -> agent.plugin.v1.Provenance
	12, // 7: agent.plugin.v1.DescribeResponse.limits:type_name -> agent.plugin.v1.ResourceLimits
	5,  // 8: agent.plugin.v1.ConfigureRequest.application_protocol:type_name -> agent.plugin.v1.ProtocolVersion
	8,  // 9: agent.plugin.v1.ConfigureRequest.grants:type_name -> agent.plugin.v1.CapabilityGrant
	12, // 10: agent.plugin.v1.ConfigureRequest.limits:type_name -> agent.plugin.v1.ResourceLimits
	7,  // 11: agent.plugin.v1.ConfigureResponse.enabled_capabilities:type_name -> agent.plugin.v1.CapabilityVersion
	12, // 12: agent.plugin.v1.ConfigureResponse.effective_limits:type_name -> agent.plugin.v1.ResourceLimits
	0,  // 13: agent.plugin.v1.ReadyResponse.status:type_name -> agent.plugin.v1.ReadinessStatus
	1,  // 14: agent.plugin.v1.HealthResponse.status:type_name -> agent.plugin.v1.HealthStatus
	2,  // 15: agent.plugin.v1.ShutdownRequest.mode:type_name -> agent.plugin.v1.ShutdownMode
	3,  // 16: agent.plugin.v1.ToolHints.risk:type_name -> agent.plugin.v1.RiskHint
	24, // 17: agent.plugin.v1.ToolDescriptor.hints:type_name -> agent.plugin.v1.ToolHints
	25, // 18: agent.plugin.v1.ListToolsResponse.tools:type_name -> agent.plugin.v1.ToolDescriptor
	29, // 19: agent.plugin.v1.ToolResult.content:type_name -> agent.plugin.v1.ToolContent
	4,  // 20: agent.plugin.v1.ToolFailure.code:type_name -> agent.plugin.v1.FailureCode
	31, // 21: agent.plugin.v1.ToolFailure.problems:type_name -> agent.plugin.v1.FailureProblem
	28, // 22: agent.plugin.v1.InvokeToolResponse.progress:type_name -> agent.plugin.v1.ToolProgress
	30, // 23: agent.plugin.v1.InvokeToolResponse.result:type_name -> agent.plugin.v1.ToolResult
	32, // 24: agent.plugin.v1.InvokeToolResponse.failure:type_name -> agent.plugin.v1.ToolFailure
	13, // 25: agent.plugin.v1.CoreService.Describe:input_type -> agent.plugin.v1.DescribeRequest
	15, // 26: agent.plugin.v1.CoreService.Configure:input_type -> agent.plugin.v1.ConfigureRequest
	17, // 27: agent.plugin.v1.CoreService.Ready:input_type -> agent.plugin.v1.ReadyRequest
	19, // 28: agent.plugin.v1.CoreService.Health:input_type -> agent.plugin.v1.HealthRequest
	21, // 29: agent.plugin.v1.CoreService.Shutdown:input_type -> agent.plugin.v1.ShutdownRequest
	23, // 30: agent.plugin.v1.ToolsService.ListTools:input_type -> agent.plugin.v1.ListToolsRequest
	27, // 31: agent.plugin.v1.ToolsService.InvokeTool:input_type -> agent.plugin.v1.InvokeToolRequest
	14, // 32: agent.plugin.v1.CoreService.Describe:output_type -> agent.plugin.v1.DescribeResponse
	16, // 33: agent.plugin.v1.CoreService.Configure:output_type -> agent.plugin.v1.ConfigureResponse
	18, // 34: agent.plugin.v1.CoreService.Ready:output_type -> agent.plugin.v1.ReadyResponse
	20, // 35: agent.plugin.v1.CoreService.Health:output_type -> agent.plugin.v1.HealthResponse
	22, // 36: agent.plugin.v1.CoreService.Shutdown:output_type -> agent.plugin.v1.ShutdownResponse
	26, // 37: agent.plugin.v1.ToolsService.ListTools:output_type -> agent.plugin.v1.ListToolsResponse
	33, // 38: agent.plugin.v1.ToolsService.InvokeTool:output_type -> agent.plugin.v1.InvokeToolResponse
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_agent_plugin_v1_plugin_proto_init() }
func file_agent_plugin_v1_plugin_proto_init() {
	if File_agent_plugin_v1_plugin_proto != nil {
		return
	}
	file_agent_plugin_v1_plugin_proto_msgTypes[28].OneofWrappers = []any{
		(*InvokeToolResponse_Progress)(nil),
		(*InvokeToolResponse_Result)(nil),
		(*InvokeToolResponse_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_plugin_v1_plugin_proto_rawDesc), len(file_agent_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_agent_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_agent_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_agent_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_agent_plugin_v1_plugin_proto = out.File
	file_agent_plugin_v1_plugin_proto_goTypes = nil
	file_agent_plugin_v1_plugin_proto_depIdxs = nil
}
