// Package httpx is the shared HTTP plumbing for provider adapters: a tuned
// transport, JSON request/response execution, SSE stream setup, an SSRF
// guard, and Retry-After parsing.
//
// Design notes, mirrored from the package design doc:
//
//   - No http.Client.Timeout is ever set: it would cap the total time to read
//     a response body and kill long streams. Callers bound requests with
//     context deadlines instead.
//   - ResponseHeaderTimeout is likewise unset because non-streaming LLM calls
//     legitimately spend minutes before the first response byte.
//   - By default the client refuses plain HTTP and connections to private,
//     loopback, link-local, or unspecified addresses (SSRF guard). Local
//     endpoints opt out via Config.
package httpx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"maps"
	"mime"
	"mime/multipart"
	"net"
	"net/http"
	"net/textproto"
	"net/url"
	"strconv"
	"syscall"
	"time"

	"github.com/rsbin1178/pips/ai/internal/jsonx"
)

// Config carries the transport-level options every provider constructor
// accepts. Provider option funcs write into it.
type Config struct {
	// APIKey is the provider credential. How it is sent (bearer header,
	// x-api-key, x-goog-api-key) is up to the adapter's Authorize hook.
	APIKey string
	// BaseURL overrides the provider's default endpoint. It should include
	// any version prefix (for example "https://api.openai.com/v1").
	BaseURL string
	// HTTPClient replaces the built-in client entirely. The bring-your-own
	// client is used as-is: transport tuning and the SSRF dial guard are the
	// owner's responsibility. Scheme checks still apply.
	HTTPClient *http.Client
	// Header is applied to every request. Adapter-set headers are written
	// first, so Header entries override them on key collision.
	Header http.Header
	// AllowHTTP permits plain-HTTP base URLs (local inference servers).
	AllowHTTP bool
	// AllowPrivateIPs disables the SSRF dial guard (local inference servers).
	AllowPrivateIPs bool
	// MaxStreamLineSize caps a single SSE line; zero selects the sse package
	// default (1 MiB).
	MaxStreamLineSize int
}

// Client executes JSON and SSE requests against one provider endpoint.
// It is built once per adapter instance and is safe for concurrent use.
type Client struct {
	httpClient *http.Client
	base       *url.URL
	header     http.Header

	maxStreamLineSize int

	// initErr defers construction failures (bad base URL, forbidden scheme)
	// to the first call, letting provider constructors stay single-valued.
	initErr error
}

// New builds a Client from cfg, falling back to defaultBaseURL when
// cfg.BaseURL is empty. Construction never fails; configuration errors
// surface on the first request.
func New(cfg Config, defaultBaseURL string) *Client {
	c := &Client{
		header:            cfg.Header.Clone(),
		maxStreamLineSize: cfg.MaxStreamLineSize,
	}

	rawURL := cfg.BaseURL
	if rawURL == "" {
		rawURL = defaultBaseURL
	}

	base, err := url.Parse(rawURL)
	if err != nil {
		c.initErr = fmt.Errorf("invalid base URL %q: %w", rawURL, err)
		return c
	}

	switch {
	case base.Scheme == "https":
	case base.Scheme == "http" && cfg.AllowHTTP:
	case base.Scheme == "http":
		c.initErr = fmt.Errorf("plain-HTTP base URL %q requires the allow-HTTP option", rawURL)
		return c
	default:
		c.initErr = fmt.Errorf("unsupported base URL scheme %q", base.Scheme)
		return c
	}

	c.base = base

	if cfg.HTTPClient != nil {
		c.httpClient = cfg.HTTPClient
	} else {
		c.httpClient = &http.Client{
			Transport: newTransport(cfg.AllowPrivateIPs),
			CheckRedirect: func(*http.Request, []*http.Request) error {
				return http.ErrUseLastResponse
			},
		}
	}

	return c
}

// MaxStreamLineSize exposes the configured SSE line ceiling for adapters.
func (c *Client) MaxStreamLineSize() int {
	return c.maxStreamLineSize
}

// ErrorDecoder turns a non-2xx response into an error. Adapters parse their
// provider's error body shape and build an *ai.Error; retryAfter is the
// parsed Retry-After header (zero when absent).
type ErrorDecoder func(status int, retryAfter time.Duration, body []byte) error

// maxErrorBodySize caps how much of an error response is read into memory.
const maxErrorBodySize = 1 << 20

// FormField is one text field of a multipart/form-data request.
type FormField struct {
	// Name is the multipart part name.
	Name string
	// Value is the field's text value.
	Value string
}

// FormFile is one binary part of a multipart/form-data request. Part names and
// filenames are generated by the adapter, never copied from caller input.
type FormFile struct {
	// Field is the multipart part name (for example "image[]").
	Field string
	// Name is the filename recorded in the part's Content-Disposition.
	Name string
	// ContentType is the part's media type. Empty omits the part header.
	ContentType string
	// Data is the part's body.
	Data []byte
}

// PostJSON executes a JSON POST and decodes the 2xx response body into out.
// It returns the raw response bytes for Response.Raw. Non-2xx responses are
// passed to decodeErr.
func (c *Client) PostJSON(ctx context.Context, path string, headers http.Header, body, out any, decodeErr ErrorDecoder) ([]byte, error) {
	payload, err := jsonx.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("encoding request body: %w", err)
	}

	return c.post(ctx, path, headers, "application/json", payload, out, decodeErr)
}

// PostMultipart executes a multipart/form-data POST and decodes the 2xx
// response body into out. The body is buffered in memory before sending so it
// can be replayed for retries; the caller bounds the payload size. Non-2xx
// responses are passed to decodeErr.
func (c *Client) PostMultipart(ctx context.Context, path string, headers http.Header, fields []FormField, files []FormFile, out any, decodeErr ErrorDecoder) ([]byte, error) {
	payload, contentType, err := encodeMultipart(fields, files)
	if err != nil {
		return nil, err
	}

	return c.post(ctx, path, headers, contentType, payload, out, decodeErr)
}

// post sends one encoded payload and decodes the 2xx response body into out.
func (c *Client) post(ctx context.Context, path string, headers http.Header, contentType string, payload []byte, out any, decodeErr ErrorDecoder) ([]byte, error) {
	resp, err := c.send(ctx, http.MethodPost, path, headers, contentType, payload) //nolint:bodyclose // closed by readJSON
	if err != nil {
		return nil, err
	}

	return c.readJSON(resp, out, decodeErr)
}

// GetJSON executes a GET request and decodes the 2xx response body into out.
// Non-2xx responses are passed to decodeErr. Task-based provider APIs use it
// to poll a previously submitted job.
func (c *Client) GetJSON(ctx context.Context, path string, headers http.Header, out any, decodeErr ErrorDecoder) ([]byte, error) {
	resp, err := c.send(ctx, http.MethodGet, path, headers, "", nil) //nolint:bodyclose // closed by readJSON
	if err != nil {
		return nil, err
	}

	return c.readJSON(resp, out, decodeErr)
}

// readJSON drains and decodes one response, mapping non-2xx status through
// decodeErr.
func (c *Client) readJSON(resp *http.Response, out any, decodeErr ErrorDecoder) ([]byte, error) {
	defer drainClose(resp.Body)

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("reading response body: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, decodeErr(resp.StatusCode, retryAfter(resp), raw)
	}

	if out != nil {
		if err := jsonx.Unmarshal(raw, out); err != nil {
			return nil, fmt.Errorf("decoding response body: %w", err)
		}
	}

	return raw, nil
}

// PostStream executes a JSON POST expecting an SSE response and returns the
// response body ready for the sse package. Non-2xx responses are fully read
// and passed to decodeErr, so stream setup failures carry provider error
// details.
func (c *Client) PostStream(ctx context.Context, path string, headers http.Header, body any, decodeErr ErrorDecoder) (io.ReadCloser, error) {
	payload, err := jsonx.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("encoding request body: %w", err)
	}

	return c.postStream(ctx, path, headers, "application/json", payload, decodeErr)
}

// PostMultipartStream executes a multipart/form-data POST expecting an SSE
// response and returns the response body ready for the sse package. Like
// [Client.PostMultipart], the body is buffered in memory before sending.
// Non-2xx responses are fully read and passed to decodeErr.
func (c *Client) PostMultipartStream(ctx context.Context, path string, headers http.Header, fields []FormField, files []FormFile, decodeErr ErrorDecoder) (io.ReadCloser, error) {
	payload, contentType, err := encodeMultipart(fields, files)
	if err != nil {
		return nil, err
	}

	return c.postStream(ctx, path, headers, contentType, payload, decodeErr)
}

// postStream sends one encoded payload and returns the SSE response body.
func (c *Client) postStream(ctx context.Context, path string, headers http.Header, contentType string, payload []byte, decodeErr ErrorDecoder) (io.ReadCloser, error) {
	if headers == nil {
		headers = http.Header{}
	}

	headers = headers.Clone()
	headers.Set("Accept", "text/event-stream")

	resp, err := c.send(ctx, http.MethodPost, path, headers, contentType, payload) //nolint:bodyclose // closed on error paths here; success body is returned to the adapter, which owns closing it
	if err != nil {
		return nil, err
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		defer drainClose(resp.Body)

		raw, readErr := io.ReadAll(io.LimitReader(resp.Body, maxErrorBodySize))
		if readErr != nil {
			return nil, fmt.Errorf("reading error body (status %d): %w", resp.StatusCode, readErr)
		}

		return nil, decodeErr(resp.StatusCode, retryAfter(resp), raw)
	}

	return resp.Body, nil
}

// encodeMultipart renders fields and files into a multipart/form-data body and
// its Content-Type header value.
func encodeMultipart(fields []FormField, files []FormFile) ([]byte, string, error) {
	var buf bytes.Buffer

	writer := multipart.NewWriter(&buf)

	for _, field := range fields {
		if err := writer.WriteField(field.Name, field.Value); err != nil {
			return nil, "", fmt.Errorf("encoding multipart field %q: %w", field.Name, err)
		}
	}

	for _, file := range files {
		if err := writeFormFile(writer, file); err != nil {
			return nil, "", err
		}
	}

	if err := writer.Close(); err != nil {
		return nil, "", fmt.Errorf("encoding multipart body: %w", err)
	}

	return buf.Bytes(), writer.FormDataContentType(), nil
}

func writeFormFile(writer *multipart.Writer, file FormFile) error {
	disposition := mime.FormatMediaType("form-data", map[string]string{
		"name":     file.Field,
		"filename": file.Name,
	})
	if disposition == "" {
		return fmt.Errorf("encoding multipart part %q: invalid name or filename", file.Field)
	}

	header := textproto.MIMEHeader{}
	header.Set("Content-Disposition", disposition)

	if file.ContentType != "" {
		header.Set("Content-Type", file.ContentType)
	}

	part, err := writer.CreatePart(header)
	if err != nil {
		return fmt.Errorf("encoding multipart part %q: %w", file.Field, err)
	}

	if _, err := part.Write(file.Data); err != nil {
		return fmt.Errorf("encoding multipart part %q: %w", file.Field, err)
	}

	return nil
}

func (c *Client) send(ctx context.Context, method, path string, headers http.Header, contentType string, payload []byte) (*http.Response, error) {
	if c.initErr != nil {
		return nil, c.initErr
	}

	u := c.base.JoinPath(path)
	// Preserve query parameters passed in the path (Gemini's ?alt=sse).
	if rawPath, query, ok := splitQuery(path); ok {
		u = c.base.JoinPath(rawPath)
		u.RawQuery = query
	}

	var body io.Reader
	if len(payload) > 0 {
		body = bytes.NewReader(payload)
	}

	req, err := http.NewRequestWithContext(ctx, method, u.String(), body)
	if err != nil {
		return nil, err
	}

	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}

	maps.Copy(req.Header, headers)
	// Config-level headers win over adapter headers.
	maps.Copy(req.Header, c.header)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	return resp, nil
}

func splitQuery(path string) (rawPath, query string, ok bool) {
	for i := range len(path) {
		if path[i] == '?' {
			return path[:i], path[i+1:], true
		}
	}

	return path, "", false
}

// retryAfter parses a Retry-After header as delay seconds or an HTTP date.
func retryAfter(resp *http.Response) time.Duration {
	value := resp.Header.Get("Retry-After")
	if value == "" {
		return 0
	}

	if secs, err := strconv.Atoi(value); err == nil && secs >= 0 {
		return time.Duration(secs) * time.Second
	}

	if at, err := http.ParseTime(value); err == nil {
		if d := time.Until(at); d > 0 {
			return d
		}
	}

	return 0
}

// drainClose drains and closes a response body so the connection is reusable.
func drainClose(body io.ReadCloser) {
	_, _ = io.Copy(io.Discard, io.LimitReader(body, maxErrorBodySize))
	_ = body.Close()
}

// newTransport builds the tuned default transport. See the package comment
// for why no header/overall timeouts appear here.
func newTransport(allowPrivateIPs bool) *http.Transport {
	dialer := &net.Dialer{
		Timeout:   10 * time.Second,
		KeepAlive: 30 * time.Second,
	}
	if !allowPrivateIPs {
		dialer.ControlContext = guardControl
	}

	return &http.Transport{
		Proxy:                 http.ProxyFromEnvironment,
		DialContext:           dialer.DialContext,
		ForceAttemptHTTP2:     true,
		MaxIdleConns:          100,
		MaxIdleConnsPerHost:   32,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: time.Second,
	}
}

// ErrPrivateAddress is returned (wrapped) when the SSRF guard blocks a dial
// to a non-public address.
var ErrPrivateAddress = errors.New("dial to private, loopback, or link-local address blocked (enable the allow-private-IPs option for local endpoints)")

// guardControl runs after DNS resolution for every connection attempt and
// rejects non-public destinations, defeating DNS-rebinding tricks.
func guardControl(_ context.Context, _, address string, _ syscall.RawConn) error {
	host, _, err := net.SplitHostPort(address)
	if err != nil {
		return fmt.Errorf("ssrf guard: %w", err)
	}

	ip := net.ParseIP(host)
	if ip == nil {
		return fmt.Errorf("ssrf guard: unexpected non-IP address %q", host)
	}

	if ip.IsLoopback() || ip.IsPrivate() || ip.IsLinkLocalUnicast() ||
		ip.IsLinkLocalMulticast() || ip.IsMulticast() || ip.IsUnspecified() {
		return fmt.Errorf("ssrf guard: %s: %w", ip, ErrPrivateAddress)
	}

	return nil
}
